export const getDisplayText = (language, text) => {
  return language === "en" ? text.en : text.pl;
};
export const getDisplayTextFromChoices = (language, en, pl) => {
  return language === "en" ? en : pl;
};

export const dictionary = {
  common: {
    update: { en: "Update", pl: "Aktualizuj" },
    add: { en: "Add", pl: "Dodaj" },
    cancel: { en: "Cancel", pl: "Cofnij" },
    choose: { en: "Choose", pl: "Wybierz" },
    delete: { en: "Delete", pl: "Usuń" },
    confirm: { en: "Confirm", pl: "Potwierdź" },
    back: { en: "Back", pl: "Wyjdź" },
    confirmDeleteText: {
      en: "Are you sure you want to delete it?",
      pl: "Czy na pewno chcesz usunąć ten element?",
    },
    confirmButtonLabel: {
      en: "Confirm",
      pl: "Potwierdzam",
    },
    confirmExitButtonLabel: {
      en: "Ok",
      pl: "Ok",
    },
    error: {
      en: "Operation did not succeed. Fix your data.",
      pl: "Operacja nie udała się. Popraw dane.",
    },
    errorMsg: {
      country: {
        en: "Cannot update/save country with this data. Maybe you are trying to add same country second time?",
        pl: "Nie można aktualizować/zapisać państwa z tymi danymi. Może dodajesz drugi raz te samo państwo?",
      },
      city: {
        en: "Cannot update/save city with this data. Maybe you are trying to add same city second time?",
        pl: "Nie można aktualizować/zapisać miasta z tymi danymi. Może dodajesz drugi raz te samo miasto?",
      },
    },
  },
  navbar: {
    home: { en: "Home", pl: "Start" },
    plates: { en: "Plates", pl: "Talerzyki" },
    gallery: { en: "Gallery", pl: "Galeria" },
    map: { en: "Map", pl: "Mapa" },
    statistics: { en: "Statistics", pl: "Statystyki" },
    world: { en: "Your World", pl: "Twój świat" },
  },
  home: {
    welcome: { en: "Welcome Traveler!", pl: "Witaj Podróżniku!" },
    have: { en: "You have: ", pl: "Masz: " },
    plates: { en: " plates, from ", pl: " talerzyków, z " },
    countries: { en: " countries, from ", pl: " krajów, z " },
    cities: { en: " cities. Congrats!", pl: " miast. Gratulacje!" },
  },
  map: {
    filters: { en: "Filters", pl: "Filtry" },
    world: { en: "World:", pl: "Świat:" },
    continent: { en: "Continent:", pl: "Kontynent:" },
    continentLabel: { en: "name", pl: "namePl" },
    country: { en: "Country:", pl: "Kraj:" },
    countryLabel: { en: "name", pl: "namePl" },
    selected: { en: "Selected:", pl: "Wybrane:" },
    hideNames: { en: "Hide name", pl: "Ukryj nazwy" },
  },
  gallery: {
    filters: { en: "Filters", pl: "Filtry" },
    all: { en: "All", pl: "Wszystkie:" },
    country: { en: "Country:", pl: "Kraj:" },
    countryLabel: { en: "name", pl: "name" },
    region: { en: "Region:", pl: "Region:" },
    regionLabel: { en: "name", pl: "name" },
  },
  world: {
    cities: {
      title: { en: "Cities:", pl: "Miasta:" },
      city: { en: "City:", pl: "Miasto" },
      cityAccessor: { en: "name", pl: "name_pl" },
      country: { en: "Country:", pl: "Kraj" },
      countryAccessor: { en: "country", pl: "country_pl" },
      region: { en: "Region:", pl: "Region" },
      regionAccessor: { en: "region", pl: "region" },
      population: { en: "Population:", pl: "Populacja" },
      populationAccessor: { en: "population", pl: "population" },
    },
    citiesDetails: {
      title: { en: "City details", pl: "Dane miasta" },
      newTitle: { en: "New city details", pl: "Dane nowego miasta" },
      cityEn: { en: "City(en)", pl: "Miasto(ang)" },
      cityPl: { en: "City(pl)", pl: "Miasto(pl)" },
      countryEn: { en: "Country(en)", pl: "Kraj(ang)" },
      countryPl: { en: "Country(pl)", pl: "Kraj(pl)" },
      region: { en: "Region", pl: "Region" },
      population: { en: "Population", pl: "Populacja" },
      latitude: { en: "Latitude", pl: "Latitude" },
      longitude: { en: "Longitude", pl: "Longitude" },
    },
    countries: {
      title: { en: "Countries:", pl: "Kraje:" },
      country: { en: "Country:", pl: "Kraj" },
      countryAccessor: { en: "name", pl: "name_pl" },
      capital: { en: "Capital:", pl: "Stolica" },
      region: { en: "Region:", pl: "Region" },
      subregion: { en: "Subregion:", pl: "Subregion" },
    },
    countriesDetails: {
      title: { en: "Country details", pl: "Dane kraju" },
      newTitle: { en: "New country details", pl: "Dane nowego kraju" },
      countryEn: { en: "Country(en)", pl: "Kraj(ang)" },
      countryPl: { en: "Country(pl)", pl: "Kraj(pl)" },
      capital: { en: "Capital", pl: "Stolica" },
      region: { en: "Region", pl: "Region" },
      subregion: { en: "Subregion:", pl: "Subregion" },
      latitude: { en: "Capital latitude", pl: "Latitude (stolicy)" },
      longitude: { en: "Capital longitude", pl: "Longitude (stolicy)" },
    },
  },
  plateDetails: {
    title: { en: "Plate details", pl: "Dane talerzyka" },
    newTitle: { en: "New plate details", pl: "Dane nowego talerzyka" },
    countryEn: { en: "Country(en)", pl: "Kraj(ang)" },
    countryPl: { en: "Country(pl)", pl: "Kraj(pl)" },
    cityEn: { en: "City(en)", pl: "Miasto(ang)" },
    cityPl: { en: "City(pl)", pl: "Miasto(pl)" },
    latitude: { en: "Latitude", pl: "Latitude" },
    longitude: { en: "Longitude", pl: "Longitude" },
    info: { en: "Info", pl: "Info" },
    image: { en: "Image", pl: "Zdjęcie" },
    filters: { en: "Filters", pl: "Filtry" },
    country: { en: "Country:", pl: "Kraj:" },
    city: { en: "City:", pl: "Miasto:" },
    countryLabel: { en: "name", pl: "name_pl" },
    cityLabel: { en: "name", pl: "name_pl" },
    is_country_plate: { en: "Country plate?", pl: "Talerzyk kraju?" },
  },
  plateList: {
    country: { en: "Country", pl: "Kraj" },
    countryAccessor: { en: "country", pl: "country_pl" },
    city: { en: "City", pl: "Miasto" },
    cityAccessor: { en: "city", pl: "city_pl" },
    image: { en: "Image?", pl: "Zdjęcie?" },
    is_country_plate: { en: "Country plate?", pl: "Talerzyk kraju?" },
  },
  statistics: {
    country: { en: "Country", pl: "Kraj" },
    count: { en: "Count", pl: "Liczba" },
    cities: { en: "Cities", pl: "Miasta" },
  },
};
